---
#
# Set up a gmail relay server
# We default to using msmtp
# ssmtp isn't actively developed
# postfix and sendmail is overkill
#
# sysrc requires community.general v2.5.9

- hosts: mailrelay
  become: true

  tasks:
    - name: Configure gmail relay on Ubuntu
      block:
        - name: Install msmtp-mta
          ansible.builtin.apt:
            name: msmtp-mta
            state: present

        - name: Copy msmtp configuration file
          ansible.builtin.copy:
            src: private/msmtp/msmtprc
            dest: /etc/msmtprc
            owner: root
            group: msmtp
            mode: '0640'
            backup: true

        - name: Install bsd-mailx
          ansible.builtin.apt:
            name: bsd-mailx
            state: present

      when: (ansible_facts['distribution'] == 'Ubuntu') or 
        (ansible_facts['distribution'] == 'Debian')

    - name: Configure gmail relay on FreeBSD
      # We need to disable default sendmail on FreeBSD
      block:
        - name: Disable sendmail
          community.general.sysrc:
            name: sendmail_enable
            state: present
            value: "NO"

        - name: Disable sendmail_submit
          community.general.sysrc:
            name: sendmail_submit
            state: present
            value: "NO"

        - name: Disable sendmail_outbound
          community.general.sysrc:
            name: sendmail_outbound
            state: present
            value: "NO"

        - name: Disable sendmail_msq_queue
          community.general.sysrc:
            name: sendmail_msp_queue_enable
            state: present
            value: "NO"

        - name: Uninstall ssmtp if it's there
          pkgng:
            name: ssmtp
            state: absent

        - name: Install msmtp
          pkgng:
            name: msmtp
            state: present

        - name: Copy msmtp configuration file
          ansible.builtin.copy:
            src: private/msmtp/msmtprc
            dest: /usr/local/etc/msmtprc
            owner: root
            group: wheel
            mode: '0640'
            backup: true

        - name: Copy mailer.conf file
          ansible.builtin.copy:
            src: files/msmtp/mailer.conf
            dest: /etc/mail/mailer.conf
            owner: root
            group: wheel
            mode: '0644'
            backup: true

      when: ansible_distribution == "FreeBSD"
