---
#
# Set up a nagios monitoring server
#

- hosts: nagios
  become: yes

  tasks:
      - name: Disable sendmail
        lineinfile:
          path: /etc/rc.conf
          regexp: '^sendmail_enable.*'
          line: 'sendmail_enable="NO"'
        when: 0 > 1

      - name: Disable sendmail_submit
        lineinfile:
          path: /etc/rc.conf
          regexp: '^sendmail_submit_enable'
          line: 'sendmail_submit_enable="NO"'
        when: 0 > 1

      - name: Disable sendmail_outbound
        lineinfile:
          path: /etc/rc.conf
          regexp: '^sendmail_outbound_enable'
          line: 'sendmail_outbound_enable="NO"'
        when: 0 > 1

      - name: Disable sendmail_msq_queue
        lineinfile:
          path: /etc/rc.conf
          regexp: '^sendmail_msp_queue_enable'
          line: 'sendmail_msp_queue_enable="NO"'
        when: 0 > 1

      - name: Uninstall ssmtp
        pkgng:
          name: ssmtp
          state: absent

      - name: Install msmtp
        pkgng:
          name: msmtp
          state: present

      - name: Install apache24
        pkgng:
          name: apache24
          state: present

      - name: Set ServerAdmin email
        lineinfile:
          path: /usr/local/etc/apache24/httpd.conf
          regexp: "^ServerAdmin "
          line: "ServerAdmin larry@daberko.com"

      - name: Set ServerName
        lineinfile:
          path: /usr/local/etc/apache24/httpd.conf
          regexp: "^#?ServerName "
          line: "ServerName {{inventory_hostname}}"

      - name: Enable mod_cgi
        replace:
          path: /usr/local/etc/apache24/httpd.conf
          regexp: '#LoadModule cgi_module libexec/apache24/mod_cgi.so'
          replace: 'LoadModule cgi_module libexec/apache24/mod_cgi.so'
  
      - name: Install PHP80
        pkgng:
          name: php80
          state: present

      - name: Install mod_php80
        pkgng:
          name: mod_php80
          state: present

      - name: Copy php.ini file from production sample file
        command:
          cmd: /bin/cp /usr/local/etc/php.ini-production /usr/local/etc/php.ini
          creates: /usr/local/etc/php.ini
          
      - name: Add mod_php config to Apache
        ansible.builtin.copy:
          src: /home/ldaberko/Documents/it/ansible/files/nagios/apache/001_mod-php.conf
          dest: /usr/local/etc/apache24/modules.d/001_mod-php.conf
          owner: root
          group: wheel
          mode: 0644

      - name: Make sure php_module is loaded in httpd.conf
        lineinfile:
          path: /usr/local/etc/apache24/httpd.conf
          regexp: '^LoadModule php_module'
          insertafter: '^#?LoadModule rewrite_module'
          line: LoadModule php_module libexec/apache24/libphp.so
          backup: yes
          
      - name: Install nagios
        pkgng:
          name: nagios
          state: present

      - name: Install nrpe3
        pkgng:
          name: nrpe3
          state: present

      - name: Add nagios to apache config
        copy:
          src: /home/ldaberko/Documents/it/ansible/files/nagios/apache/nagios.conf
          dest: /usr/local/etc/apache24/Includes/
          owner: root
          group: wheel
          mode: 0644

      - name: Copy htpasswd file
        ansible.builtin.copy:
          src: /home/ldaberko/Documents/it/ansible/files/nagios/htpasswd.users
          dest: /usr/local/etc/nagios/htpasswd.users
          owner: root
          group: wheel
          mode: 0644

      - name: Copy nagios main cfg files
        copy:
          src: "/home/ldaberko/Documents/it/ansible/files/nagios/{{item}}"
          dest: "/usr/local/etc/nagios/"
          owner: root
          group: wheel
          mode: 0644
        loop:
          - cgi.cfg
          - nagios.cfg
          - resource.cfg

      - name: Copy nagios objects cfg files
        copy:
          src: "/home/ldaberko/Documents/it/ansible/files/nagios/objects/{{item}}"
          dest: "/usr/local/etc/nagios/objects/"
          owner: root
          group: wheel
          mode: 0644
        loop:
          - commands.cfg
          - contacts.cfg
          - localhost.cfg
          - templates.cfg
          - timeperiods.cfg

      - name: Enable and start apache24
        service:
          name: apache24
          enabled: yes
          state: restarted

      - name: Enable and start nagios
        service:
          name: nagios
          enabled: yes
          state: restarted
