---
#
# Set up a nagios monitoring server
#

- hosts: nagiosserver
  become: true

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:

    - name: Install nagios server on Ubuntu and Debian
      block:

        - name: Check for msmtp-mta installation
          ansible.builtin.fail:
            msg: msmtp-mta package is missing
          when: '"msmtp-mta" not in ansible_facts.packages'

        - name: Check for bsd-mailx installation
          ansible.builtin.fail:
            msg: bsd-mailx package is missing
          when: '"bsd-mailx" not in ansible_facts.packages'

        - name: Install nagios packages
          ansible.builtin.apt:
            update_cache: true
            name:
              - nagios4
              - nagios-nrpe-plugin
            state: present

        - name: Enable cgi module for Apache2
          community.general.apache2_module:
            name: cgi
            state: present

        - name: Restart apache for cgi module
          ansible.builtin.service:
            name: apache2
            state: restarted

      when: ansible_facts['distribution'] == 'Ubuntu' or
        ansible_facts['distribution'] == 'Debian'
